[tool.poetry]
name = "alfred"
version = "0.1.0"
description = ""
authors = ["Tyler Knotek <tyler@7ekkno.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
rumps = "^0.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
