"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['alfred-assist.py']
OPTIONS = {
    'iconfile': 'assets/alfred-assist.icns',
    'argv_emulation': True,
    'plist': {
        'LSUIElement': True,
    },
    'packages': ['rumps'],
}

setup(
    name='Alfred Assist',
    app=APP,
    data_files=['assets'],
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
